apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pool
  template:
    metadata:
      labels:
        app: worker-pool
    spec:
      containers:
        - name: worker-pool
          image: worker-pool:latest
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: QUEUE_NAME
              value: "ml-tasks"
